server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/school_blog?UseUnicode=true&characterEncoding=UTF-8
      username: user
      password: 123456
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: blog_

jueding:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
