server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/school_blog?UseUnicode=true&characterEncoding=UTF-8
      username: user
      password: 123456
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: blog_
